[package]
name = "bevy_saga_impl"
version = "0.1.0"
edition = "2024"

[lib]

[dependencies]
bevy = { version = "0.16", default-features = false }
variadics_please = "1.1.0"
crabtime = "1.1.3"

[dev-dependencies]
bevy_saga_macros = { path = "../bevy_saga_macros" }
proc-macro2 = "1"
quote = "1"