[package]
name = "bevy_event_flow"
version = "0.1.0"
edition = "2024"

[lib]

[dependencies]
bevy = { version = "0.16", default-features = false }

[dev-dependencies]
bevy_event_flow_macros = { path = "../bevy_event_flow_macros" }
