[package]
name = "bevy_saga"
version = "0.1.0"
edition = "2024"

[lib]

[dependencies]
bevy = { version = "0.16", default-features = false }
variadics_please = "1.1.0"

[dev-dependencies]
bevy_saga_macros = { path = "../bevy_saga_macros" }